import Header from "@/shared/components/Header"
import Providers from "@/shared/components/Providers/Providers"
import { ColorSchemeScript, MantineProvider } from "@mantine/core"
import "@mantine/core/styles.css"
import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import { ReactNode } from "react"
import "../styles/globals.css"
import "../styles/reset.css"

const nunito = Nunito({
	subsets: ["cyrillic"],
	variable: "--font-nunito",
	weight: ["400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
	title: "Next Pizza",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript defaultColorScheme="dark" />
			</head>
			<body className={nunito.className}>{<Providers>{children}</Providers>}</body>
		</html>
	)
}
