import Header from "@/shared/components/Header"
import QueryProvider from "@/shared/components/QueryProvider/QueryProvider"
import { ColorSchemeScript, MantineProvider } from "@mantine/core"
import "@mantine/core/styles.css"
import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "../styles/globals.css"
import theme from "../styles/mantineTheme"
import "../styles/reset.css"

const nunito = Nunito({
	subsets: ["cyrillic"],
	variable: "--font-nunito",
	weight: ["400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
	title: "Next Pizza",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<QueryProvider>
			<html lang="en">
				<head>
					<ColorSchemeScript />
				</head>
				<body className={nunito.className}>
					<MantineProvider
						theme={theme}
						defaultColorScheme="light"
					>
						<Header />
						{children}
					</MantineProvider>
				</body>
			</html>
		</QueryProvider>
	)
}
